name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 4 * * 2' # every Tuesday at 4am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16
  PNPM_VERSION: 8

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
    - name: Lint
      run: pnpm lint
    - name: Run Tests
      run: pnpm test:ember

  floating:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: test

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      run: rm pnpm-lock.yaml && pnpm install
    - name: Run Tests
      run: pnpm test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    needs: test

    strategy:
      fail-fast: true
      matrix:
        try-scenario:
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
    - name: Run Tests
      run: pnpm test:ember-try-one ${{ matrix.try-scenario }}
