name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 4 * * 2' # every Tuesday at 4am

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

env:
  NODE_VERSION: '12'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '${{ env.NODE_VERSION }}'
        cache: yarn
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Lint
      run: yarn lint
    - name: Run Tests
      run: yarn test:ember

  floating:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: test

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '${{ env.NODE_VERSION }}'
        cache: yarn
    - name: Install Dependencies
      run: yarn install --no-lockfile --non-interactive
    - name: Run Tests
      run: yarn test:ember

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true
    needs: test

    strategy:
      fail-fast: true
      matrix:
        try-scenario:
          - ember-lts-3.24
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic
          - embroider-safe
          - embroider-optimized

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '${{ env.NODE_VERSION }}'
        cache: yarn
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    - name: Run Tests
      run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
